#16  Add support for Dropwizard Metrics 4.0.0
Simplified maven dependencies and avoid NoClassdefFoundErrors when one or the other Metrics library is missing